services:

  app-frontend:
    build:
      context: .
      dockerfile: app-frontend/Dockerfile
    depends_on:
      - ms-gateway
    ports:
      - "3025:3025"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://0.0.0.0:3025
      - NEXT_PUBLIC_API_URL=http://ms-users:3000 # par exemple si ms-gateway
      - NEXTAUTH_SECRET=une_cle_secrete_tres_forte_dans_env_shared

  ms-users:
    build:
      context: .
      dockerfile: backend/ms-users/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:ZienrLetWa7gw1MQ@db.wrivqparegjwiklfzsuq.supabase.co:5432/postgres
      - PORT=3001
      - JWT_SECRET=une_cle_secrete_tres_forte_dans_env_shared
      - JWT_EXPIRES_IN=7d
      - HOST=0.0.0.0
      - SUPABASE_URL=https://wrivqparegjwiklfzsuq.supabase.co
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyaXZxcGFyZWdqd2lrbGZ6c3VxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTI1MTg1MiwiZXhwIjoyMDYwODI3ODUyfQ.5OBB1uIifIYessGI4Nhz7YvbX5jzlOYVnd_kDzPtfoE
    volumes:
      - /app/node_modules

  ms-friends:
    build:
      context: .
      dockerfile: backend/ms-friends/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://postgres:ZienrLetWa7gw1MQ@db.wrivqparegjwiklfzsuq.supabase.co:5432/postgres
      - PORT=3002
      - HOST=0.0.0.0
    volumes:
      - /app/node_modules

  ms-leaderboard:
    build:
      context: .
      dockerfile: backend/ms-leaderboard/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://postgres:ZienrLetWa7gw1MQ@db.wrivqparegjwiklfzsuq.supabase.co:5432/postgres
      - PORT=3003
      - HOST=0.0.0.0
    volumes:
      - /app/node_modules

  ms-game-cinema-1:
    build:
      context: .
      dockerfile: backend/ms-game-cinema-1/Dockerfile
    depends_on:
      - ms-users
    ports:
      - "3004:3004"
    environment:
      - IS_DOCKER=true
      - DATABASE_URL=postgresql://postgres:ZienrLetWa7gw1MQ@db.wrivqparegjwiklfzsuq.supabase.co:5432/postgres
      - PORT=3004
      - HOST=0.0.0.0
    volumes:
      - /app/node_modules
      
  ms-game-cinema-2:
    build:
      context: .
      dockerfile: backend/ms-game-cinema-2/Dockerfile
    depends_on:
      - ms-users
    ports:
      - "3005:3005"
    environment:
      - IS_DOCKER=true
      - DATABASE_URL=postgresql://postgres:ZienrLetWa7gw1MQ@db.wrivqparegjwiklfzsuq.supabase.co:5432/postgres
      - PORT=3005
      - HOST=0.0.0.0
    volumes:
      - /app/node_modules
      

  ms-gateway:
    build:
      context: .
      dockerfile: backend/ms-gateway/Dockerfile
    depends_on:
      - ms-users
      - ms-friends
      - ms-game-cinema-1
      - ms-game-cinema-2
      - ms-leaderboard

    ports:
      - "3000:3000"
    environment:
      - IS_DOCKER=true
      - PORT=3000
      - JWT_SECRET=une_cle_secrete_tres_forte
      - JWT_EXPIRES_IN=7d
    volumes:
      - /app/node_modules

