name: CICD
run-name: ${{ github.actor }} déploie sur ${{ github.ref_name }}

on:
    push:
        branches:
            - main
            - dev
        tags:
            - v*

jobs:
    audit:
        name: Audit des dépendances
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - run: pnpm audit

    lint:
        name: Lint du code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - run: pnpm lint

    test:
        name: Tests unitaires
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - run: pnpm test

    build:
        name: Build de l'application
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: true
            - run: pnpm build

    deploy-production:
        name: Build & Push Docker (production)
        if: github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')
        needs: [audit, lint, test, build]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker image (prod)
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ghcr.io/christophersemard/dailychallenge/dailychallenge:latest
                      ghcr.io/christophersemard/dailychallenge/dailychallenge:${{ github.ref_name }}

    deploy-dev:
        name: Build & Push Docker (dev)
        if: github.ref_name == 'dev'
        needs: [audit, lint, test, build]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker image (dev)
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ghcr.io/christophersemard/dailychallenge/dailychallenge:dev
