name: DailyChallenge CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [app-frontend, ms-gateway, ms-users]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install
              working-directory: ${{ matrix.service }}

            - name: Lint
              run: pnpm lint
              working-directory: ${{ matrix.service }}

            - name: Test
              run: pnpm test
              working-directory: ${{ matrix.service }}

            - name: Build
              run: pnpm build
              working-directory: ${{ matrix.service }}
